//go:build integration

// Code generated by Tester Agent. DO NOT EDIT.
// Task: Write integration tests for synchronous hierarchy inference in graph-ingest
// Builder must make these tests pass without modification.

package graphingest

import (
	"context"
	"encoding/json"
	"fmt"
	"testing"
	"time"

	"github.com/c360studio/semengine/graph"
	"github.com/c360studio/semengine/message"
	"github.com/c360studio/semengine/vocabulary"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The pin read EntityState.Version to say how often a key had been written. Design D15
// removes Version and leaves the KV revision as the only fence, and ENTITY_STATES keeps
// one revision per key, so these tests check what each write left in the stored state:
// an entity's stored revision is its birth's, and every statement it holds is held once.

// statementCount returns how many of triples state predicate with object.
func statementCount(triples []message.Triple, predicate string, object any) int {
	n := 0
	for _, triple := range triples {
		if triple.Predicate == predicate && triple.Object == object {
			n++
		}
	}
	return n
}

// assertEachStatementOnce fails if entity holds any statement more than once.
func assertEachStatementOnce(t *testing.T, entity graph.EntityState) {
	t.Helper()
	seen := make(map[string]int)
	for _, triple := range entity.Triples {
		seen[fmt.Sprintf("%s %s %v", triple.Subject, triple.Predicate, triple.Object)]++
	}
	var repeated []string
	for statement, n := range seen {
		if n > 1 {
			repeated = append(repeated, fmt.Sprintf("%s (%d times)", statement, n))
		}
	}
	assert.Empty(t, repeated, "%s holds a statement more than once", entity.ID)
}

// ====================================================================================
// Synchronous Hierarchy Tests - Core Behavior
// ====================================================================================

func TestComponent_SynchronousHierarchy_IncludedBeforeWrite(t *testing.T) {
	tests := []struct {
		name              string
		entityID          string
		expectHierarchy   bool
		expectedTripleMin int // Minimum triples expected (base + hierarchy)
		reason            string
	}{
		{
			name:              "valid_entity",
			entityID:          "c360.platform.robotics.mav1.drone.test001",
			expectHierarchy:   true,
			expectedTripleMin: 4, // 1 base triple + 3 hierarchy membership edges
			reason:            "6-part entity should get hierarchy triples before KV write",
		},
		{
			name:              "container_entity_excluded",
			entityID:          "c360.platform.robotics.mav1.drone.group",
			expectHierarchy:   false,
			expectedTripleMin: 1, // Only base triple, no hierarchy (prevents infinite cascade)
			reason:            "container entities should not get hierarchy edges",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			// Create entity
			entity := &graph.EntityState{
				ID:          tt.entityID,
				MessageType: testEntityType(),
				Triples: withTestMetadata(
					message.Triple{
						Subject:   tt.entityID,
						Predicate: "entity.type.class",
						Object:    "test.entity",
						Timestamp: time.Now(),
					},
				),
				UpdatedAt: time.Now(),
			}

			// Write entity - hierarchy should be applied synchronously. CreateEntity
			// is this call with the birth's revision dropped.
			_, birthRevision, err := comp.createEntityWithReceipt(ctx, entity)
			require.NoError(t, err, tt.reason)

			// Read back from KV - should already contain hierarchy triples
			entry, err := comp.entityBucket.Get(ctx, tt.entityID)
			require.NoError(t, err, "entity should exist in KV bucket")

			var storedEntity graph.EntityState
			err = json.Unmarshal(entry.Value, &storedEntity)
			require.NoError(t, err)

			// Verify entity was written once, with hierarchy triples included. The
			// pin asserted Version == 1; with Version gone (design D15) the stored
			// revision must be the birth's: a later write would have replaced it.
			assert.Equal(t, birthRevision, entry.Revision, "entity should be written once")
			assertEachStatementOnce(t, storedEntity)
			assert.GreaterOrEqual(t, len(storedEntity.Triples), tt.expectedTripleMin,
				"%s: expected at least %d triples", tt.reason, tt.expectedTripleMin)

			if tt.expectHierarchy {
				// Verify hierarchy membership edges are present
				hierarchyTriples := 0
				for _, triple := range storedEntity.Triples {
					if triple.Context == "inference.hierarchy" {
						hierarchyTriples++
					}
				}
				assert.GreaterOrEqual(t, hierarchyTriples, 3,
					"entity should have at least 3 hierarchy triples (type, system, domain)")
			} else {
				// Verify NO hierarchy edges for container entities
				for _, triple := range storedEntity.Triples {
					assert.NotEqual(t, "inference.hierarchy", triple.Context,
						"container entities should not have hierarchy edges")
				}
			}
		})
	}
}

// entity-id-audit:classify intentional-malformed "c360.platform.robotics.mav1.drone" line=529 column=24 surface=go-field:.entityID entity_id_invalid:arity five-part hierarchy ID rejection fixture
// entity-id-audit:classify intentional-malformed "c360.platform.robotics.mav1.drone.test001.extra" line=537 column=24 surface=go-field:.entityID entity_id_invalid:arity seven-part hierarchy ID rejection fixture

func TestComponent_SynchronousHierarchy_SingleWrite(t *testing.T) {
	tests := []struct {
		name     string
		entityID string
	}{
		{
			name:     "entity_version_is_one",
			entityID: "c360.platform.sensors.hvac.temperature.test001",
		},
		{
			name:     "no_update_cascade",
			entityID: "c360.platform.robotics.mav1.drone.test002",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			// Create entity
			entity := &graph.EntityState{
				ID:          tt.entityID,
				MessageType: testEntityType(),
				Triples: withTestMetadata(
					message.Triple{
						Subject:   tt.entityID,
						Predicate: "entity.type.class",
						Object:    "test.entity",
						Timestamp: time.Now(),
					},
				),
				UpdatedAt: time.Now(),
			}

			// Write entity. CreateEntity is this call with the birth's revision dropped.
			_, birthRevision, err := comp.createEntityWithReceipt(ctx, entity)
			require.NoError(t, err)

			// Read back immediately - should have been written once
			entry, err := comp.entityBucket.Get(ctx, tt.entityID)
			require.NoError(t, err)

			var storedEntity graph.EntityState
			err = json.Unmarshal(entry.Value, &storedEntity)
			require.NoError(t, err)

			// CRITICAL: Entity must be written once with all triples. A second write
			// means AddTriple was called after initial write (async pattern). The pin
			// read Version == 1; design D15 removes Version, so the stored revision
			// must be the birth's: a later write would have replaced it.
			assert.Equal(t, birthRevision, entry.Revision,
				"entity must be written once - no cascade updates allowed")
			assertEachStatementOnce(t, storedEntity)

			// Verify hierarchy triples are present despite single write
			hierarchyTriples := 0
			for _, triple := range storedEntity.Triples {
				if triple.Context == "inference.hierarchy" {
					hierarchyTriples++
				}
			}
			assert.GreaterOrEqual(t, hierarchyTriples, 3,
				"hierarchy triples must be included in initial write")
		})
	}
}

func TestComponent_SynchronousHierarchy_ContainerCreation(t *testing.T) {
	tests := []struct {
		name        string
		containerID string
		level       string
		contains    string
	}{
		{
			name:        "type_container",
			containerID: "c360.platform.robotics.mav1.drone.group",
			level:       "type",
			contains:    vocabulary.HierarchyTypeContains,
		},
		{
			name:        "system_container",
			containerID: "c360.platform.robotics.mav1.group.container",
			level:       "system",
			contains:    vocabulary.HierarchySystemContains,
		},
		{
			name:        "domain_container",
			containerID: "c360.platform.robotics.group.container.level",
			level:       "domain",
			contains:    vocabulary.HierarchyDomainContains,
		},
	}

	ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)

	defer cancelOperation()

	comp := createTestComponentWithHierarchyConfig(t, true)

	owner := newGraphIngestTestOwner(comp)

	defer owner.finish(ctx, t)

	require.NoError(t, comp.Initialize())

	require.NoError(t, comp.Start(owner.startContext(ctx)))

	// Create a single entity that triggers all container creation
	entityID := "c360.platform.robotics.mav1.drone.test001"
	entity := &graph.EntityState{
		ID:          entityID,
		MessageType: testEntityType(),
		Triples: withTestMetadata(
			message.Triple{
				Subject:   entityID,
				Predicate: "entity.type.class",
				Object:    "robotics.drone",
				Timestamp: time.Now(),
			},
		),
		UpdatedAt: time.Now(),
	}

	// Write entity - containers should be created synchronously
	require.NoError(t, comp.CreateEntity(ctx, entity))

	// Verify all containers exist immediately (no async delay needed)
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			entry, err := comp.entityBucket.Get(ctx, tt.containerID)
			require.NoError(t, err, "container %s should exist immediately after entity write", tt.containerID)

			var containerEntity graph.EntityState
			err = json.Unmarshal(entry.Value, &containerEntity)
			require.NoError(t, err)

			// Verify container has type classification, once
			assert.Equal(t, 1, statementCount(containerEntity.Triples, "entity.type.class", "hierarchy.container"),
				"container should hold its type classification once")

			// Verify container ID format
			assert.Equal(t, tt.containerID, containerEntity.ID)

			// Verify the container took its one inverse contains edge, to the entity.
			// The pin asserted Version == 1, which counted the inverse edge's bump on
			// a container born at Version 0 (pin hierarchy.go:482 sets no Version;
			// addTripleLane bumps it). Design D15 removes Version, so what that one
			// append leaves is checked: one contains edge, and it names the entity.
			assert.Equal(t, 1, statementCount(containerEntity.Triples, tt.contains, entityID),
				"container should hold its inverse %s edge to the entity once", tt.contains)
			members := 0
			for _, triple := range containerEntity.Triples {
				if triple.Predicate == tt.contains {
					members++
				}
			}
			assert.Equal(t, 1, members, "container should hold one %s edge: the entity is its only member", tt.contains)
			assertEachStatementOnce(t, containerEntity)
		})
	}
}

func TestComponent_SynchronousHierarchy_MultipleEntitiesSameType(t *testing.T) {
	ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
	defer cancelOperation()
	comp := createTestComponentWithHierarchyConfig(t, true)
	owner := newGraphIngestTestOwner(comp)
	defer owner.finish(ctx, t)

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(owner.startContext(ctx)))

	// Create multiple entities that share type container
	entities := []string{
		"c360.platform.robotics.mav1.drone.test001",
		"c360.platform.robotics.mav1.drone.test002",
		"c360.platform.robotics.mav1.drone.test003",
	}

	for _, entityID := range entities {
		entity := &graph.EntityState{
			ID:          entityID,
			MessageType: testEntityType(),
			Triples: withTestMetadata(
				message.Triple{
					Subject:   entityID,
					Predicate: "entity.type.class",
					Object:    "robotics.drone",
					Timestamp: time.Now(),
				},
			),
			UpdatedAt: time.Now(),
		}
		require.NoError(t, comp.CreateEntity(ctx, entity))
	}

	t.Run("shared_containers", func(t *testing.T) {
		// Verify shared type container exists (created once, reused)
		typeContainerID := "c360.platform.robotics.mav1.drone.group"
		entry, err := comp.entityBucket.Get(ctx, typeContainerID)
		require.NoError(t, err)

		var containerEntity graph.EntityState
		err = json.Unmarshal(entry.Value, &containerEntity)
		require.NoError(t, err)

		// Container should exist with type classification
		hasTypeTriple := false
		for _, triple := range containerEntity.Triples {
			if triple.Predicate == "entity.type.class" && triple.Object == "hierarchy.container" {
				hasTypeTriple = true
				break
			}
		}
		assert.True(t, hasTypeTriple, "container should have type classification")
	})

	t.Run("all_inverse_edges_present", func(t *testing.T) {
		// Verify container has inverse edges to ALL entities
		// This tests that synchronous updates don't lose edges due to race conditions
		typeContainerID := "c360.platform.robotics.mav1.drone.group"
		entry, err := comp.entityBucket.Get(ctx, typeContainerID)
		require.NoError(t, err)

		var containerEntity graph.EntityState
		err = json.Unmarshal(entry.Value, &containerEntity)
		require.NoError(t, err)

		// Count inverse edges (hierarchy.type.contains)
		inverseEdgeCount := 0
		foundEntities := make(map[string]bool)
		for _, triple := range containerEntity.Triples {
			if triple.Predicate == vocabulary.HierarchyTypeContains {
				// Verify object is one of our entities
				for _, entityID := range entities {
					if triple.Object == entityID {
						foundEntities[entityID] = true
						inverseEdgeCount++
						break
					}
				}
			}
		}

		// CRITICAL: All 3 entities should have inverse edges
		// Async watcher pattern loses edges due to concurrent updates
		// Synchronous pattern preserves all edges
		assert.Equal(t, 3, inverseEdgeCount,
			"container should have 3 inverse edges (one per entity)")
		assert.Equal(t, 3, len(foundEntities),
			"all 3 entities should be found in inverse edges")
	})
}

// ====================================================================================
// Lifecycle Tests - No Watcher
// ====================================================================================

func TestComponent_SynchronousHierarchy_NoWatcherLifecycle(t *testing.T) {
	tests := []struct {
		name   string
		verify func(ctx context.Context, t *testing.T, comp *Component)
	}{
		{
			name: "no_start_stop_methods",
			verify: func(_ context.Context, t *testing.T, comp *Component) {
				// HierarchyInference should not have Start/Stop methods
				// This test verifies Builder removed them during refactor
				// If this test fails to compile, it means Builder properly removed Start/Stop
				// If it compiles and runs, Builder did NOT remove them (failure)

				// Builder: hierarchyInference should be created but never have Start/Stop called
				// The fact that this test compiles after refactor means Start/Stop were removed
				assert.NotNil(t, comp.hierarchyInference,
					"hierarchy inference should exist as stateless utility")
			},
		},
		{
			name: "stateless_utility",
			verify: func(ctx context.Context, t *testing.T, comp *Component) {
				// Verify HierarchyInference works immediately without Start()

				entity := &graph.EntityState{
					ID:          "c360.platform.test.system.type.instance001",
					MessageType: testEntityType(),
					Triples: withTestMetadata(
						message.Triple{
							Subject:   "c360.platform.test.system.type.instance001",
							Predicate: "entity.type.class",
							Object:    "test.entity",
							Timestamp: time.Now(),
						},
					),
					UpdatedAt: time.Now(),
				}

				// Should work without calling Start() on hierarchyInference
				require.NoError(t, comp.CreateEntity(ctx, entity))

				// Verify hierarchy worked
				entry, err := comp.entityBucket.Get(ctx, entity.ID)
				require.NoError(t, err)

				var storedEntity graph.EntityState
				err = json.Unmarshal(entry.Value, &storedEntity)
				require.NoError(t, err)

				// Should have hierarchy triples despite never calling Start()
				hierarchyTriples := 0
				for _, triple := range storedEntity.Triples {
					if triple.Context == "inference.hierarchy" {
						hierarchyTriples++
					}
				}
				assert.GreaterOrEqual(t, hierarchyTriples, 3,
					"hierarchy should work as stateless utility (no Start needed)")
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			tt.verify(ctx, t, comp)
		})
	}
}

func TestComponent_SynchronousHierarchy_DisabledConfig(t *testing.T) {
	t.Run("no_hierarchy_triples_when_disabled", func(t *testing.T) {
		// When enable_hierarchy: false, no hierarchy triples should be added
		ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
		defer cancelOperation()
		comp := createTestComponentWithHierarchyConfig(t, false)
		owner := newGraphIngestTestOwner(comp)
		defer owner.finish(ctx, t)

		require.NoError(t, comp.Initialize())
		require.NoError(t, comp.Start(owner.startContext(ctx)))

		entityID := "c360.platform.robotics.mav1.drone.test001"
		entity := &graph.EntityState{
			ID:          entityID,
			MessageType: testEntityType(),
			Triples: withTestMetadata(
				message.Triple{
					Subject:   entityID,
					Predicate: "entity.type.class",
					Object:    "robotics.drone",
					Timestamp: time.Now(),
				},
			),
			UpdatedAt: time.Now(),
		}

		require.NoError(t, comp.CreateEntity(ctx, entity))

		// Read back and verify NO hierarchy triples
		entry, err := comp.entityBucket.Get(ctx, entityID)
		require.NoError(t, err)

		var storedEntity graph.EntityState
		err = json.Unmarshal(entry.Value, &storedEntity)
		require.NoError(t, err)

		// Should only have the base triple (no hierarchy); the ADR-054
		// indexing-profile stamp is framework metadata, not a hierarchy triple.
		assert.Equal(t, 1, nonProfileTripleCount(&storedEntity),
			"disabled hierarchy should not add any triples")

		for _, triple := range storedEntity.Triples {
			assert.NotEqual(t, "inference.hierarchy", triple.Context,
				"no hierarchy context when disabled")
		}

		// Verify no containers created
		containerIDs := []string{
			"c360.platform.robotics.mav1.drone.group",
			"c360.platform.robotics.mav1.group.container",
			"c360.platform.robotics.group.container.level",
		}

		for _, containerID := range containerIDs {
			_, err := comp.entityBucket.Get(ctx, containerID)
			assert.Error(t, err, "container %s should not exist when hierarchy disabled", containerID)
		}
	})
}

// ====================================================================================
// Edge Case Tests
// ====================================================================================

func TestComponent_SynchronousHierarchy_InvalidEntityID(t *testing.T) {
	tests := []struct {
		name               string
		entityID           string
		expectedTriples    int
		expectHierarchy    bool
		reason             string
		shouldFailValidate bool
	}{
		{
			name:               "five_part_id_skipped",
			entityID:           "c360.platform.robotics.mav1.drone",
			expectedTriples:    0,
			expectHierarchy:    false,
			reason:             "5-part IDs should fail validation (not skip hierarchy)",
			shouldFailValidate: true,
		},
		{
			name:               "seven_part_id_skipped",
			entityID:           "c360.platform.robotics.mav1.drone.test001.extra",
			expectedTriples:    0,
			expectHierarchy:    false,
			reason:             "7-part IDs should fail validation (not skip hierarchy)",
			shouldFailValidate: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			entity := &graph.EntityState{
				ID:          tt.entityID,
				MessageType: testEntityType(),
				Triples: []message.Triple{
					{
						Subject:   tt.entityID,
						Predicate: "entity.type.class",
						Object:    "test.entity",
						Timestamp: time.Now(),
					},
				},
				UpdatedAt: time.Now(),
			}

			err := comp.CreateEntity(ctx, entity)

			if tt.shouldFailValidate {
				// Entity ID validation should reject invalid formats
				assert.Error(t, err, tt.reason)
			} else {
				// Entity accepted but hierarchy skipped
				require.NoError(t, err, tt.reason)

				entry, err := comp.entityBucket.Get(ctx, tt.entityID)
				require.NoError(t, err)

				var storedEntity graph.EntityState
				err = json.Unmarshal(entry.Value, &storedEntity)
				require.NoError(t, err)

				if tt.expectHierarchy {
					hierarchyTriples := 0
					for _, triple := range storedEntity.Triples {
						if triple.Context == "inference.hierarchy" {
							hierarchyTriples++
						}
					}
					assert.GreaterOrEqual(t, hierarchyTriples, 3,
						"valid entity should have hierarchy triples")
				} else {
					// No hierarchy triples for invalid formats
					for _, triple := range storedEntity.Triples {
						assert.NotEqual(t, "inference.hierarchy", triple.Context,
							"invalid entity ID format should skip hierarchy")
					}
				}
			}
		})
	}
}

func TestComponent_SynchronousHierarchy_ContextCancellation(t *testing.T) {
	t.Run("respects_cancelled_context", func(t *testing.T) {
		ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
		defer cancelOperation()
		comp := createTestComponentWithHierarchyConfig(t, true)
		owner := newGraphIngestTestOwner(comp)
		defer owner.finish(ctx, t)

		require.NoError(t, comp.Initialize())
		require.NoError(t, comp.Start(owner.startContext(ctx)))

		// Create cancelled context
		cancelledCtx, cancel := context.WithCancel(ctx)
		cancel()

		entityID := "c360.platform.robotics.mav1.drone.test001"
		entity := &graph.EntityState{
			ID:          entityID,
			MessageType: testEntityType(),
			Triples: withTestMetadata(
				message.Triple{
					Subject:   entityID,
					Predicate: "entity.type.class",
					Object:    "robotics.drone",
					Timestamp: time.Now(),
				},
			),
			UpdatedAt: time.Now(),
		}

		// Should fail or return quickly with context error
		err := comp.CreateEntity(cancelledCtx, entity)

		// Either operation failed (context cancelled) or completed before checking context
		// Either is acceptable - just verify it doesn't hang
		if err != nil {
			assert.ErrorIs(t, err, context.Canceled,
				"should return context.Canceled error")
		}

		// Verify operation completed quickly (not hung)
		// If we got here, test passed (no timeout)
	})
}

// ====================================================================================
// No sibling edges - ruling G (#91 comment 6062681355)
// ====================================================================================

// TestComponent_SynchronousHierarchy_NoSiblingEdges: three births of one type each
// carry their type-membership statement, and none of the three entities holds a
// hierarchy.type.sibling statement once all three are born, so no birth wrote one on
// itself or on an entity born before it. The predicate stays registered in vocabulary.
func TestComponent_SynchronousHierarchy_NoSiblingEdges(t *testing.T) {
	ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
	defer cancelOperation()
	comp := createTestComponentWithHierarchyConfig(t, true)
	owner := newGraphIngestTestOwner(comp)
	defer owner.finish(ctx, t)

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(owner.startContext(ctx)))

	entityIDs := []string{
		"c360.platform.sensors.hvac.pressure.press001",
		"c360.platform.sensors.hvac.pressure.press002",
		"c360.platform.sensors.hvac.pressure.press003",
	}
	for _, entityID := range entityIDs {
		entity := &graph.EntityState{
			ID:          entityID,
			MessageType: testEntityType(),
			Triples: withTestMetadata(
				message.Triple{
					Subject:   entityID,
					Predicate: "entity.type.class",
					Object:    "sensor.pressure",
					Timestamp: time.Now(),
				},
			),
			UpdatedAt: time.Now(),
		}
		require.NoError(t, comp.CreateEntity(ctx, entity))
	}

	for _, entityID := range entityIDs {
		entry, err := comp.entityBucket.Get(ctx, entityID)
		require.NoError(t, err)
		var stored graph.EntityState
		require.NoError(t, json.Unmarshal(entry.Value, &stored))

		assert.Equal(t, 1, countPredicate(stored.Triples, vocabulary.HierarchyTypeMember),
			"%s: the birth ran the inference", entityID)
		assert.Zero(t, countPredicate(stored.Triples, vocabulary.HierarchyTypeSibling),
			"%s: no birth writes a sibling statement", entityID)
	}
}

// countPredicate counts the triples that state predicate.
func countPredicate(triples []message.Triple, predicate string) int {
	count := 0
	for _, triple := range triples {
		if triple.Predicate == predicate {
			count++
		}
	}
	return count
}
