//go:build integration

// Code generated by Tester Agent. DO NOT EDIT.
// Task: Write integration tests for synchronous hierarchy inference in graph-ingest
// Builder must make these tests pass without modification.

package graphingest

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/c360studio/semengine/graph"
	"github.com/c360studio/semengine/message"
	"github.com/c360studio/semengine/vocabulary"
	"github.com/nats-io/nats.go/jetstream"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// entityWrites counts the writes to graph-ingest's entity bucket from the moment
// watchEntityWrites returns. The pin read EntityState.Version to say how often a key
// had been written; design D15 removes Version and leaves the KV revision as the only
// fence, and ENTITY_STATES keeps one revision per key, so the writes are counted off a
// watcher instead.
type entityWrites struct {
	watcher jetstream.KeyWatcher
	counts  map[string]int
	last    uint64
}

// watchEntityWrites starts counting. The watcher first replays each key's current
// value and then sends nil; those replayed values are not writes made since, so they
// are passed over.
func watchEntityWrites(ctx context.Context, t *testing.T, comp *Component) *entityWrites {
	t.Helper()
	watcher, err := comp.entityBucket.Watch(ctx, ">")
	require.NoError(t, err)
	t.Cleanup(func() { _ = watcher.Stop() })
	ew := &entityWrites{watcher: watcher, counts: make(map[string]int)}
	for {
		select {
		case <-ctx.Done():
			t.Fatalf("entity bucket watcher: no end of its initial values: %v", ctx.Err())
		case entry, ok := <-watcher.Updates():
			if !ok {
				t.Fatal("entity bucket watcher closed before the end of its initial values")
			}
			if entry == nil {
				return ew
			}
			ew.last = max(ew.last, entry.Revision())
		}
	}
}

// writesTo returns how many times key has been written since watchEntityWrites. It
// reads the watcher until it has delivered the key's stored revision; the watcher
// delivers in revision order, so every earlier write has been counted by then.
func (ew *entityWrites) writesTo(ctx context.Context, t *testing.T, comp *Component, key string) int {
	t.Helper()
	entry, err := comp.entityBucket.Get(ctx, key)
	require.NoError(t, err)
	for ew.last < entry.Revision {
		select {
		case <-ctx.Done():
			t.Fatalf("entity bucket watcher: revision %d of %s not delivered (last %d): %v",
				entry.Revision, key, ew.last, ctx.Err())
		case update, ok := <-ew.watcher.Updates():
			if !ok {
				t.Fatalf("entity bucket watcher closed before revision %d of %s", entry.Revision, key)
			}
			ew.counts[update.Key()]++
			ew.last = update.Revision()
		}
	}
	return ew.counts[key]
}

// ====================================================================================
// Synchronous Hierarchy Tests - Core Behavior
// ====================================================================================

func TestComponent_SynchronousHierarchy_IncludedBeforeWrite(t *testing.T) {
	tests := []struct {
		name              string
		entityID          string
		expectHierarchy   bool
		expectedTripleMin int // Minimum triples expected (base + hierarchy)
		reason            string
	}{
		{
			name:              "valid_entity",
			entityID:          "c360.platform.robotics.mav1.drone.test001",
			expectHierarchy:   true,
			expectedTripleMin: 4, // 1 base triple + 3 hierarchy membership edges
			reason:            "6-part entity should get hierarchy triples before KV write",
		},
		{
			name:              "container_entity_excluded",
			entityID:          "c360.platform.robotics.mav1.drone.group",
			expectHierarchy:   false,
			expectedTripleMin: 1, // Only base triple, no hierarchy (prevents infinite cascade)
			reason:            "container entities should not get hierarchy edges",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			// Create entity
			entity := &graph.EntityState{
				ID:          tt.entityID,
				MessageType: testEntityType(),
				Triples: []message.Triple{
					{
						Subject:   tt.entityID,
						Predicate: "entity.type.class",
						Object:    "test.entity",
						Timestamp: time.Now(),
					},
				},
				UpdatedAt: time.Now(),
			}

			// Write entity - hierarchy should be applied synchronously
			writes := watchEntityWrites(ctx, t, comp)
			require.NoError(t, comp.CreateEntity(ctx, entity), tt.reason)

			// Read back from KV - should already contain hierarchy triples
			entry, err := comp.entityBucket.Get(ctx, tt.entityID)
			require.NoError(t, err, "entity should exist in KV bucket")

			var storedEntity graph.EntityState
			err = json.Unmarshal(entry.Value, &storedEntity)
			require.NoError(t, err)

			// Verify entity was written with hierarchy triples included
			// The pin asserted Version == 1; with Version gone (design D15) the
			// writes to the key are counted.
			assert.Equal(t, 1, writes.writesTo(ctx, t, comp, tt.entityID), "entity should be written once")
			assert.GreaterOrEqual(t, len(storedEntity.Triples), tt.expectedTripleMin,
				"%s: expected at least %d triples", tt.reason, tt.expectedTripleMin)

			if tt.expectHierarchy {
				// Verify hierarchy membership edges are present
				hierarchyTriples := 0
				for _, triple := range storedEntity.Triples {
					if triple.Context == "inference.hierarchy" {
						hierarchyTriples++
					}
				}
				assert.GreaterOrEqual(t, hierarchyTriples, 3,
					"entity should have at least 3 hierarchy triples (type, system, domain)")
			} else {
				// Verify NO hierarchy edges for container entities
				for _, triple := range storedEntity.Triples {
					assert.NotEqual(t, "inference.hierarchy", triple.Context,
						"container entities should not have hierarchy edges")
				}
			}
		})
	}
}

// entity-id-audit:classify intentional-malformed "c360.platform.robotics.mav1.drone" line=529 column=24 surface=go-field:.entityID entity_id_invalid:arity five-part hierarchy ID rejection fixture
// entity-id-audit:classify intentional-malformed "c360.platform.robotics.mav1.drone.test001.extra" line=537 column=24 surface=go-field:.entityID entity_id_invalid:arity seven-part hierarchy ID rejection fixture

func TestComponent_SynchronousHierarchy_SingleWrite(t *testing.T) {
	tests := []struct {
		name     string
		entityID string
	}{
		{
			name:     "entity_version_is_one",
			entityID: "c360.platform.sensors.hvac.temperature.test001",
		},
		{
			name:     "no_update_cascade",
			entityID: "c360.platform.robotics.mav1.drone.test002",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			// Create entity
			entity := &graph.EntityState{
				ID:          tt.entityID,
				MessageType: testEntityType(),
				Triples: []message.Triple{
					{
						Subject:   tt.entityID,
						Predicate: "entity.type.class",
						Object:    "test.entity",
						Timestamp: time.Now(),
					},
				},
				UpdatedAt: time.Now(),
			}

			// Write entity
			writes := watchEntityWrites(ctx, t, comp)
			require.NoError(t, comp.CreateEntity(ctx, entity))

			// Read back immediately - should have been written once
			entry, err := comp.entityBucket.Get(ctx, tt.entityID)
			require.NoError(t, err)

			var storedEntity graph.EntityState
			err = json.Unmarshal(entry.Value, &storedEntity)
			require.NoError(t, err)

			// CRITICAL: Entity must be written once with all triples. A second write
			// means AddTriple was called after initial write (async pattern). The pin
			// read Version == 1; design D15 removes Version, so the writes to the key
			// are counted.
			assert.Equal(t, 1, writes.writesTo(ctx, t, comp, tt.entityID),
				"entity must be written once - no cascade updates allowed")

			// Verify hierarchy triples are present despite single write
			hierarchyTriples := 0
			for _, triple := range storedEntity.Triples {
				if triple.Context == "inference.hierarchy" {
					hierarchyTriples++
				}
			}
			assert.GreaterOrEqual(t, hierarchyTriples, 3,
				"hierarchy triples must be included in initial write")
		})
	}
}

func TestComponent_SynchronousHierarchy_ContainerCreation(t *testing.T) {
	tests := []struct {
		name        string
		containerID string
		level       string
	}{
		{
			name:        "type_container",
			containerID: "c360.platform.robotics.mav1.drone.group",
			level:       "type",
		},
		{
			name:        "system_container",
			containerID: "c360.platform.robotics.mav1.group.container",
			level:       "system",
		},
		{
			name:        "domain_container",
			containerID: "c360.platform.robotics.group.container.level",
			level:       "domain",
		},
	}

	ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)

	defer cancelOperation()

	comp := createTestComponentWithHierarchyConfig(t, true)

	owner := newGraphIngestTestOwner(comp)

	defer owner.finish(ctx, t)

	require.NoError(t, comp.Initialize())

	require.NoError(t, comp.Start(owner.startContext(ctx)))

	// Create a single entity that triggers all container creation
	entityID := "c360.platform.robotics.mav1.drone.test001"
	entity := &graph.EntityState{
		ID:          entityID,
		MessageType: testEntityType(),
		Triples: []message.Triple{
			{
				Subject:   entityID,
				Predicate: "entity.type.class",
				Object:    "robotics.drone",
				Timestamp: time.Now(),
			},
		},
		UpdatedAt: time.Now(),
	}

	// Write entity - containers should be created synchronously
	writes := watchEntityWrites(ctx, t, comp)
	require.NoError(t, comp.CreateEntity(ctx, entity))

	// Verify all containers exist immediately (no async delay needed)
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			entry, err := comp.entityBucket.Get(ctx, tt.containerID)
			require.NoError(t, err, "container %s should exist immediately after entity write", tt.containerID)

			var containerEntity graph.EntityState
			err = json.Unmarshal(entry.Value, &containerEntity)
			require.NoError(t, err)

			// Verify container has type classification
			hasTypeTriple := false
			for _, triple := range containerEntity.Triples {
				if triple.Predicate == "entity.type.class" && triple.Object == "hierarchy.container" {
					hasTypeTriple = true
					break
				}
			}
			assert.True(t, hasTypeTriple, "container should have type classification")

			// Verify container ID format
			assert.Equal(t, tt.containerID, containerEntity.ID)

			// Verify the container was born once and took its one inverse contains
			// edge: two writes. The pin asserted Version == 1, which counted the
			// inverse edge's bump on a container born at Version 0 (pin
			// hierarchy.go:482 sets no Version; addTripleLane bumps it). Design D15
			// removes Version, so the writes to the key are counted.
			assert.Equal(t, 2, writes.writesTo(ctx, t, comp, tt.containerID),
				"container should be written twice: its birth and its inverse contains edge")
		})
	}
}

func TestComponent_SynchronousHierarchy_MultipleEntitiesSameType(t *testing.T) {
	ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
	defer cancelOperation()
	comp := createTestComponentWithHierarchyConfig(t, true)
	owner := newGraphIngestTestOwner(comp)
	defer owner.finish(ctx, t)

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(owner.startContext(ctx)))

	// Create multiple entities that share type container
	entities := []string{
		"c360.platform.robotics.mav1.drone.test001",
		"c360.platform.robotics.mav1.drone.test002",
		"c360.platform.robotics.mav1.drone.test003",
	}

	for _, entityID := range entities {
		entity := &graph.EntityState{
			ID:          entityID,
			MessageType: testEntityType(),
			Triples: []message.Triple{
				{
					Subject:   entityID,
					Predicate: "entity.type.class",
					Object:    "robotics.drone",
					Timestamp: time.Now(),
				},
			},
			UpdatedAt: time.Now(),
		}
		require.NoError(t, comp.CreateEntity(ctx, entity))
	}

	t.Run("shared_containers", func(t *testing.T) {
		// Verify shared type container exists (created once, reused)
		typeContainerID := "c360.platform.robotics.mav1.drone.group"
		entry, err := comp.entityBucket.Get(ctx, typeContainerID)
		require.NoError(t, err)

		var containerEntity graph.EntityState
		err = json.Unmarshal(entry.Value, &containerEntity)
		require.NoError(t, err)

		// Container should exist with type classification
		hasTypeTriple := false
		for _, triple := range containerEntity.Triples {
			if triple.Predicate == "entity.type.class" && triple.Object == "hierarchy.container" {
				hasTypeTriple = true
				break
			}
		}
		assert.True(t, hasTypeTriple, "container should have type classification")
	})

	t.Run("all_inverse_edges_present", func(t *testing.T) {
		// Verify container has inverse edges to ALL entities
		// This tests that synchronous updates don't lose edges due to race conditions
		typeContainerID := "c360.platform.robotics.mav1.drone.group"
		entry, err := comp.entityBucket.Get(ctx, typeContainerID)
		require.NoError(t, err)

		var containerEntity graph.EntityState
		err = json.Unmarshal(entry.Value, &containerEntity)
		require.NoError(t, err)

		// Count inverse edges (hierarchy.type.contains)
		inverseEdgeCount := 0
		foundEntities := make(map[string]bool)
		for _, triple := range containerEntity.Triples {
			if triple.Predicate == vocabulary.HierarchyTypeContains {
				// Verify object is one of our entities
				for _, entityID := range entities {
					if triple.Object == entityID {
						foundEntities[entityID] = true
						inverseEdgeCount++
						break
					}
				}
			}
		}

		// CRITICAL: All 3 entities should have inverse edges
		// Async watcher pattern loses edges due to concurrent updates
		// Synchronous pattern preserves all edges
		assert.Equal(t, 3, inverseEdgeCount,
			"container should have 3 inverse edges (one per entity)")
		assert.Equal(t, 3, len(foundEntities),
			"all 3 entities should be found in inverse edges")
	})
}

// ====================================================================================
// Lifecycle Tests - No Watcher
// ====================================================================================

func TestComponent_SynchronousHierarchy_NoWatcherLifecycle(t *testing.T) {
	tests := []struct {
		name   string
		verify func(ctx context.Context, t *testing.T, comp *Component)
	}{
		{
			name: "no_start_stop_methods",
			verify: func(_ context.Context, t *testing.T, comp *Component) {
				// HierarchyInference should not have Start/Stop methods
				// This test verifies Builder removed them during refactor
				// If this test fails to compile, it means Builder properly removed Start/Stop
				// If it compiles and runs, Builder did NOT remove them (failure)

				// Builder: hierarchyInference should be created but never have Start/Stop called
				// The fact that this test compiles after refactor means Start/Stop were removed
				assert.NotNil(t, comp.hierarchyInference,
					"hierarchy inference should exist as stateless utility")
			},
		},
		{
			name: "stateless_utility",
			verify: func(ctx context.Context, t *testing.T, comp *Component) {
				// Verify HierarchyInference works immediately without Start()

				entity := &graph.EntityState{
					ID:          "c360.platform.test.system.type.instance001",
					MessageType: testEntityType(),
					Triples: []message.Triple{
						{
							Subject:   "c360.platform.test.system.type.instance001",
							Predicate: "entity.type.class",
							Object:    "test.entity",
							Timestamp: time.Now(),
						},
					},
					UpdatedAt: time.Now(),
				}

				// Should work without calling Start() on hierarchyInference
				require.NoError(t, comp.CreateEntity(ctx, entity))

				// Verify hierarchy worked
				entry, err := comp.entityBucket.Get(ctx, entity.ID)
				require.NoError(t, err)

				var storedEntity graph.EntityState
				err = json.Unmarshal(entry.Value, &storedEntity)
				require.NoError(t, err)

				// Should have hierarchy triples despite never calling Start()
				hierarchyTriples := 0
				for _, triple := range storedEntity.Triples {
					if triple.Context == "inference.hierarchy" {
						hierarchyTriples++
					}
				}
				assert.GreaterOrEqual(t, hierarchyTriples, 3,
					"hierarchy should work as stateless utility (no Start needed)")
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			tt.verify(ctx, t, comp)
		})
	}
}

func TestComponent_SynchronousHierarchy_DisabledConfig(t *testing.T) {
	t.Run("no_hierarchy_triples_when_disabled", func(t *testing.T) {
		// When enable_hierarchy: false, no hierarchy triples should be added
		ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
		defer cancelOperation()
		comp := createTestComponentWithHierarchyConfig(t, false)
		owner := newGraphIngestTestOwner(comp)
		defer owner.finish(ctx, t)

		require.NoError(t, comp.Initialize())
		require.NoError(t, comp.Start(owner.startContext(ctx)))

		entityID := "c360.platform.robotics.mav1.drone.test001"
		entity := &graph.EntityState{
			ID:          entityID,
			MessageType: testEntityType(),
			Triples: []message.Triple{
				{
					Subject:   entityID,
					Predicate: "entity.type.class",
					Object:    "robotics.drone",
					Timestamp: time.Now(),
				},
			},
			UpdatedAt: time.Now(),
		}

		require.NoError(t, comp.CreateEntity(ctx, entity))

		// Read back and verify NO hierarchy triples
		entry, err := comp.entityBucket.Get(ctx, entityID)
		require.NoError(t, err)

		var storedEntity graph.EntityState
		err = json.Unmarshal(entry.Value, &storedEntity)
		require.NoError(t, err)

		// Should only have the base triple (no hierarchy); the ADR-054
		// indexing-profile stamp is framework metadata, not a hierarchy triple.
		assert.Equal(t, 1, nonProfileTripleCount(&storedEntity),
			"disabled hierarchy should not add any triples")

		for _, triple := range storedEntity.Triples {
			assert.NotEqual(t, "inference.hierarchy", triple.Context,
				"no hierarchy context when disabled")
		}

		// Verify no containers created
		containerIDs := []string{
			"c360.platform.robotics.mav1.drone.group",
			"c360.platform.robotics.mav1.group.container",
			"c360.platform.robotics.group.container.level",
		}

		for _, containerID := range containerIDs {
			_, err := comp.entityBucket.Get(ctx, containerID)
			assert.Error(t, err, "container %s should not exist when hierarchy disabled", containerID)
		}
	})
}

// ====================================================================================
// Edge Case Tests
// ====================================================================================

func TestComponent_SynchronousHierarchy_InvalidEntityID(t *testing.T) {
	tests := []struct {
		name               string
		entityID           string
		expectedTriples    int
		expectHierarchy    bool
		reason             string
		shouldFailValidate bool
	}{
		{
			name:               "five_part_id_skipped",
			entityID:           "c360.platform.robotics.mav1.drone",
			expectedTriples:    0,
			expectHierarchy:    false,
			reason:             "5-part IDs should fail validation (not skip hierarchy)",
			shouldFailValidate: true,
		},
		{
			name:               "seven_part_id_skipped",
			entityID:           "c360.platform.robotics.mav1.drone.test001.extra",
			expectedTriples:    0,
			expectHierarchy:    false,
			reason:             "7-part IDs should fail validation (not skip hierarchy)",
			shouldFailValidate: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
			defer cancelOperation()
			comp := createTestComponentWithHierarchyConfig(t, true)
			owner := newGraphIngestTestOwner(comp)
			defer owner.finish(ctx, t)

			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(owner.startContext(ctx)))

			entity := &graph.EntityState{
				ID:          tt.entityID,
				MessageType: testEntityType(),
				Triples: []message.Triple{
					{
						Subject:   tt.entityID,
						Predicate: "entity.type.class",
						Object:    "test.entity",
						Timestamp: time.Now(),
					},
				},
				UpdatedAt: time.Now(),
			}

			err := comp.CreateEntity(ctx, entity)

			if tt.shouldFailValidate {
				// Entity ID validation should reject invalid formats
				assert.Error(t, err, tt.reason)
			} else {
				// Entity accepted but hierarchy skipped
				require.NoError(t, err, tt.reason)

				entry, err := comp.entityBucket.Get(ctx, tt.entityID)
				require.NoError(t, err)

				var storedEntity graph.EntityState
				err = json.Unmarshal(entry.Value, &storedEntity)
				require.NoError(t, err)

				if tt.expectHierarchy {
					hierarchyTriples := 0
					for _, triple := range storedEntity.Triples {
						if triple.Context == "inference.hierarchy" {
							hierarchyTriples++
						}
					}
					assert.GreaterOrEqual(t, hierarchyTriples, 3,
						"valid entity should have hierarchy triples")
				} else {
					// No hierarchy triples for invalid formats
					for _, triple := range storedEntity.Triples {
						assert.NotEqual(t, "inference.hierarchy", triple.Context,
							"invalid entity ID format should skip hierarchy")
					}
				}
			}
		})
	}
}

func TestComponent_SynchronousHierarchy_ContextCancellation(t *testing.T) {
	t.Run("respects_cancelled_context", func(t *testing.T) {
		ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
		defer cancelOperation()
		comp := createTestComponentWithHierarchyConfig(t, true)
		owner := newGraphIngestTestOwner(comp)
		defer owner.finish(ctx, t)

		require.NoError(t, comp.Initialize())
		require.NoError(t, comp.Start(owner.startContext(ctx)))

		// Create cancelled context
		cancelledCtx, cancel := context.WithCancel(ctx)
		cancel()

		entityID := "c360.platform.robotics.mav1.drone.test001"
		entity := &graph.EntityState{
			ID:          entityID,
			MessageType: testEntityType(),
			Triples: []message.Triple{
				{
					Subject:   entityID,
					Predicate: "entity.type.class",
					Object:    "robotics.drone",
					Timestamp: time.Now(),
				},
			},
			UpdatedAt: time.Now(),
		}

		// Should fail or return quickly with context error
		err := comp.CreateEntity(cancelledCtx, entity)

		// Either operation failed (context cancelled) or completed before checking context
		// Either is acceptable - just verify it doesn't hang
		if err != nil {
			assert.ErrorIs(t, err, context.Canceled,
				"should return context.Canceled error")
		}

		// Verify operation completed quickly (not hung)
		// If we got here, test passed (no timeout)
	})
}

// ====================================================================================
// Sibling Edge Tests - Entities with same type get bidirectional sibling edges
// ====================================================================================

func TestComponent_SynchronousHierarchy_SiblingEdges(t *testing.T) {
	t.Run("creates_bidirectional_sibling_edges", func(t *testing.T) {
		ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
		defer cancelOperation()
		comp := createTestComponentWithHierarchyConfig(t, true)
		owner := newGraphIngestTestOwner(comp)
		defer owner.finish(ctx, t)

		require.NoError(t, comp.Initialize())
		require.NoError(t, comp.Start(owner.startContext(ctx)))

		// Create first entity - no siblings yet
		entity1ID := "c360.platform.sensors.hvac.temperature.sensor001"
		entity1 := &graph.EntityState{
			ID:          entity1ID,
			MessageType: testEntityType(),
			Triples: []message.Triple{
				{
					Subject:   entity1ID,
					Predicate: "entity.type.class",
					Object:    "sensor.temperature",
					Timestamp: time.Now(),
				},
			},
			UpdatedAt: time.Now(),
		}

		require.NoError(t, comp.CreateEntity(ctx, entity1))

		// Verify first entity has hierarchy triples but no sibling triples
		entry1, err := comp.entityBucket.Get(ctx, entity1ID)
		require.NoError(t, err)

		var stored1 graph.EntityState
		err = json.Unmarshal(entry1.Value, &stored1)
		require.NoError(t, err)

		siblingCount1 := countSiblingTriples(stored1.Triples)
		assert.Equal(t, 0, siblingCount1, "first entity should have no sibling edges initially")

		// Create second entity of same type - should create bidirectional sibling edges
		entity2ID := "c360.platform.sensors.hvac.temperature.sensor002"
		entity2 := &graph.EntityState{
			ID:          entity2ID,
			MessageType: testEntityType(),
			Triples: []message.Triple{
				{
					Subject:   entity2ID,
					Predicate: "entity.type.class",
					Object:    "sensor.temperature",
					Timestamp: time.Now(),
				},
			},
			UpdatedAt: time.Now(),
		}

		require.NoError(t, comp.CreateEntity(ctx, entity2))

		// Verify second entity has sibling edge to first
		entry2, err := comp.entityBucket.Get(ctx, entity2ID)
		require.NoError(t, err)

		var stored2 graph.EntityState
		err = json.Unmarshal(entry2.Value, &stored2)
		require.NoError(t, err)

		siblingCount2 := countSiblingTriples(stored2.Triples)
		assert.Equal(t, 1, siblingCount2, "second entity should have 1 sibling edge to first")

		// Verify sibling edge points to first entity
		hasSiblingToEntity1 := false
		for _, triple := range stored2.Triples {
			if triple.Predicate == vocabulary.HierarchyTypeSibling {
				if obj, ok := triple.Object.(string); ok && obj == entity1ID {
					hasSiblingToEntity1 = true
				}
			}
		}
		assert.True(t, hasSiblingToEntity1, "second entity should have sibling edge to first")

		// Verify first entity was updated with sibling edge to second
		entry1Updated, err := comp.entityBucket.Get(ctx, entity1ID)
		require.NoError(t, err)

		var stored1Updated graph.EntityState
		err = json.Unmarshal(entry1Updated.Value, &stored1Updated)
		require.NoError(t, err)

		hasSiblingToEntity2 := false
		for _, triple := range stored1Updated.Triples {
			if triple.Predicate == vocabulary.HierarchyTypeSibling {
				if obj, ok := triple.Object.(string); ok && obj == entity2ID {
					hasSiblingToEntity2 = true
				}
			}
		}
		assert.True(t, hasSiblingToEntity2, "first entity should have been updated with sibling edge to second")
	})

	t.Run("creates_sibling_edges_for_multiple_entities", func(t *testing.T) {
		ctx, cancelOperation := context.WithTimeout(t.Context(), 60*time.Second)
		defer cancelOperation()
		comp := createTestComponentWithHierarchyConfig(t, true)
		owner := newGraphIngestTestOwner(comp)
		defer owner.finish(ctx, t)

		require.NoError(t, comp.Initialize())
		require.NoError(t, comp.Start(owner.startContext(ctx)))

		// Create 3 entities of same type
		entityIDs := []string{
			"c360.platform.sensors.hvac.pressure.press001",
			"c360.platform.sensors.hvac.pressure.press002",
			"c360.platform.sensors.hvac.pressure.press003",
		}

		for _, entityID := range entityIDs {
			entity := &graph.EntityState{
				ID:          entityID,
				MessageType: testEntityType(),
				Triples: []message.Triple{
					{
						Subject:   entityID,
						Predicate: "entity.type.class",
						Object:    "sensor.pressure",
						Timestamp: time.Now(),
					},
				},
				UpdatedAt: time.Now(),
			}
			require.NoError(t, comp.CreateEntity(ctx, entity))
		}

		// Verify third entity has 2 sibling edges (to first and second)
		entry3, err := comp.entityBucket.Get(ctx, entityIDs[2])
		require.NoError(t, err)

		var stored3 graph.EntityState
		err = json.Unmarshal(entry3.Value, &stored3)
		require.NoError(t, err)

		siblingCount3 := countSiblingTriples(stored3.Triples)
		assert.Equal(t, 2, siblingCount3, "third entity should have 2 sibling edges")

		// Verify first entity now has 2 sibling edges (to second and third)
		entry1, err := comp.entityBucket.Get(ctx, entityIDs[0])
		require.NoError(t, err)

		var stored1 graph.EntityState
		err = json.Unmarshal(entry1.Value, &stored1)
		require.NoError(t, err)

		siblingCount1 := countSiblingTriples(stored1.Triples)
		assert.Equal(t, 2, siblingCount1, "first entity should have 2 sibling edges (updated by second and third)")
	})
}

// countSiblingTriples counts the number of hierarchy.type.sibling triples
func countSiblingTriples(triples []message.Triple) int {
	count := 0
	for _, triple := range triples {
		if triple.Predicate == vocabulary.HierarchyTypeSibling {
			count++
		}
	}
	return count
}
