// Code generated by Tester Agent. DO NOT EDIT.
// Task: graph-ingest refactor - metrics handling tests
// Builder must make these tests pass without modification.

package graphingest

import (
	"encoding/json"
	"testing"

	"github.com/c360studio/semengine/component"
	"github.com/c360studio/semengine/graph"
	"github.com/c360studio/semengine/message"
	"github.com/c360studio/semengine/metric"
	"github.com/c360studio/semengine/natsclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ====================================================================================
// Metrics Registry Tests
// ====================================================================================

// The pin's TestGetEntitiesUpdatedMetric_NilRegistry and _ValidRegistry tested the
// package-level getter getEntitiesUpdatedMetric and its sync.Once global. Design D4
// removes both: each component builds its collectors and registers them on its own
// registry. A nil registry is TestComponent_MetricsRegistry_CreateComponent below and
// TestGraphIngestNilRegistryRegistersNothing; a valid one is
// TestGraphIngestMetricsRegisterOnItsRegistry.

func TestComponent_MetricsUpdate_EntityOperations(t *testing.T) {
	// Test that entity operations properly update metrics

	comp := createTestComponentWithMockKV(t)
	ctx := newTestContext(t)

	// Get initial metric value (may be 0 or non-zero due to other tests)
	// We only care about the delta

	// Create entity
	entity := newTestEntity("c360.platform.test.sys.type.001")
	require.NoError(t, comp.CreateEntity(ctx, entity))

	// Verify entitiesUpdated metric was incremented
	// The metric counter should have been called via Inc()
	assert.NotNil(t, comp.entitiesUpdated, "component should have entitiesUpdated metric")

	// Append a fact through the admitted mutation lane.
	triple := message.Triple{Subject: entity.ID, Predicate: "test.metric.value", Object: "updated"}
	data, err := json.Marshal(graph.AppendTriplesRequest{Triples: []message.Triple{triple}})
	require.NoError(t, err)
	_, err = comp.handleCanonicalAppend(ctx, data)
	require.NoError(t, err)

	// Metric should be incremented again
	// Note: We can't easily check the exact value due to Prometheus counter semantics,
	// but we verify the operations complete without panic
}

func TestComponent_MetricsAtomic_MessageProcessing(t *testing.T) {
	// Test that atomic metrics are properly updated during message processing

	comp := createTestComponentWithMockKV(t)

	// Initial state
	messages := comp.messagesProcessed
	bytes := comp.bytesProcessed
	errors := comp.errors

	// These should be zero initially in a fresh component
	assert.GreaterOrEqual(t, messages, int64(0))
	assert.GreaterOrEqual(t, bytes, int64(0))
	assert.GreaterOrEqual(t, errors, int64(0))

	// After operations, check DataFlow metrics are accessible
	metrics := comp.DataFlow()
	assert.GreaterOrEqual(t, metrics.MessagesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.BytesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.ErrorRate, float64(0))
}

func TestComponent_MetricsRegistry_CreateComponent(t *testing.T) {
	// Test component creation with different metrics registry scenarios

	tests := []struct {
		name           string
		provideMetrics bool
	}{
		{
			name:           "with metrics registry",
			provideMetrics: true,
		},
		{
			name:           "without metrics registry (nil)",
			provideMetrics: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			deps := newTestDependencies(t)

			if tt.provideMetrics {
				deps.MetricsRegistry = metric.NewMetricsRegistry()
			} else {
				deps.MetricsRegistry = nil
			}

			config := DefaultConfig()
			comp, err := createComponentWithDeps(t, config, deps)

			// Should succeed regardless of metrics registry presence
			assert.NoError(t, err, "component creation should succeed")
			assert.NotNil(t, comp, "component should not be nil")

			// Component should have entitiesUpdated metric (may be no-op if nil registry)
			assert.NotNil(t, comp.entitiesUpdated, "entitiesUpdated metric should be initialized")
		})
	}
}

// ====================================================================================
// Helper Functions
// ====================================================================================

func newTestDependencies(t *testing.T) component.Dependencies {
	t.Helper()

	natsClient := newTestNATSClient(t)

	return component.Dependencies{
		NATSClient:      natsClient,
		PayloadRegistry: newTestPayloadRegistry(t),
		Platform:        component.PlatformMeta{Org: testDeploymentOrg, Platform: testDeploymentPlatform},
		// MetricsRegistry intentionally not set - tests will set as needed
	}
}

// newTestNATSClient creates a NATS client for testing (unconnected)
func newTestNATSClient(t *testing.T) *natsclient.Client {
	t.Helper()

	natsClient, err := natsclient.NewClient("")
	require.NoError(t, err)

	return natsClient
}

// createComponentWithDeps creates a component with specified dependencies
func createComponentWithDeps(t *testing.T, config Config, deps component.Dependencies) (*Component, error) {
	t.Helper()

	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	comp, err := CreateGraphIngest(configJSON, deps)
	if err != nil {
		return nil, err
	}

	return comp.(*Component), nil
}
